### ISSUE TITLE
/records Unknown player

### ISSUE THREAD

**Issue by ItsNiklas** [Beezig/Beezig#13]
e.g. '/records jflkasjlf' returns this which certainly shouldn't be
(Here with shownetworkranktitle true)
![](http://puu.sh/weqFP/c43cc753bf.png)
![](http://puu.sh/weqEo/b86f9bc3b4.png)

**Comment by roccodev** [comment]
Uhm.. what's the problem? The user does not exist:
http://api.hivemc.com/v1/player/jflkasjlf

**Comment by ItsNiklas** [comment]
That the username and rank gets replaced with this long message? `Player not found or nicked player(50-50%)`
So it says `Player not found or nicked player(50-50%)'s Stats`

**Comment by roccodev** [comment]
Fixed in 636bbc5
