### ISSUE TITLE
"The WR is x.xxx away" doesn't run when getting a PB

### ISSUE THREAD

**Issue by ItsNiklas** [Beezig/Beezig#17]
When you get a new personal best, the ending message is different, and so the "the wr is xxx away" doesn't fire.
![img](http://puu.sh/wg9vu/50994157c6.png)
`§8? §cDeathRun§8 ? §3NEW PERSONAL BEST! §bYou beat your old record by §e3§b seconds, your new record is §e01:10§b!`
May need to switch to the message below saying 
> DeathRun | Username finished Nth. (X:XX:XX)

**Comment by roccodev** [comment]
You don't need to move to the User finished Nth, just check your logs folder :D

**Comment by ItsNiklas** [comment]
Fixed in  400d3cb. Now checks for a message that appears every time!
