### ISSUE TITLE
/s command

### ISSUE THREAD

**Issue by ThatToccata** [Beezig/Beezig#20]
Hiii,

This affects relatively few players but the /s command is a duplicate of a command used by staff to talk on the in-game staff chat. Is there a way to disable this feature at all?

Great work both!

:D

**Comment by ItsNiklas** [comment]
Thanks!
Fixed in 51e694b.

**Comment by roccodev** [comment]
Also, @ThatToccata would you like to have a prefix for staff chat, like @ for party chat, ! for shouts etc.?

**Comment by ThatToccata** [comment]
@RoccoDev If it's not too much trouble on your end, this would be very useful! :D

**Comment by roccodev** [comment]
I mean, any suggestions on the prefix? Like "?" or "*"

**Comment by ThatToccata** [comment]
Any of the above sound good to me!
