### ISSUE TITLE
ZZZZZZ Rank BW Adv Records

### ISSUE THREAD

**Issue by ItsNiklas** [Beezig/Beezig#24]
/records LordDeWitt returns his point based rank instead of the ZZZZZZ rank
Either
1. Hardcode the player as 1st (bad)
2. API the leaderboards for the username of 1st player

**Comment by roccodev** [comment]
Yeah, Ikr :D
We should do that upon load.

**Comment by roccodev** [comment]
Fixed in 23ff0cd
