### ISSUE TITLE
~535NPE's When viewing the Giant Map module in the Customize Display...

### ISSUE THREAD

**Issue by ItsNiklas** [Beezig/Beezig#41]
**535x**  `java.lang.NullPointerException`
`at tk.roccodev.zta.modules.gnt.MapItem.getValue(MapItem.java:22)`
`at eu.the5zig.mod.modules.StringItem.getText(StringItem.java:61)`
`at eu.the5zig.mod.modules.StringItem.render(StringItem.java:38)`
`...`
`at net.minecraft.launchwrapper.Launch.main(Launch.java:27)`

Started MC, Joined Hive, opened Customize Display (Still in main lobby), as soon as interacting with this module, the console goes crazy with this^

No idea why this happens; Giant.activeMap should be null at this point.

**Comment by roccodev** [comment]
Fixed in fcab104
