### ISSUE TITLE
AdvRec: Hold all messages before sending

### ISSUE THREAD

**Issue by ItsNiklas** [Beezig/Beezig#44]
Currenty, the entries get 'edited' and then get sent instantly. In the new 'fast' lobbies very often other messages come in between the AdvRec, because it cannot edit+send all messages fast enough.

Solution: Prepare all messages in messagesToSend & then send them in one bulk.

**Comment by roccodev** [comment]
That's what we're doing and we can't exceed the character limit unfortunately.
